whitespace changes

diff --git a/src/infopoint-html-viewer b/src/infopoint-html-viewer
--- a/src/infopoint-html-viewer
+++ b/src/infopoint-html-viewer
@@ -19,9 +19,10 @@ for xrapp in xulrunner xulrunner-`seq -s '.0 xulrunner-' 25 -1 10`.0 \
     break
   fi
 done
+
 if [ -z "$XULRUNNER" ]; then
-	echo "Could not find a supported xulrunner instance."
-	exit 1
+  echo "Could not find a supported xulrunner instance."
+  exit 1
 fi
 
 # look if we were installed somewhere or run locally
@@ -35,8 +36,8 @@ for dir in /usr/local/share/infopoint-html /usr/share/infopoint-html \
   fi
 done
 if [ -z "$APPDIR" ] ; then
-	echo "Something went wrong, I could not find my application.ini :(";
-	exit 1
+  echo "Something went wrong, I could not find my application.ini :(";
+  exit 1
 fi
 
 echo starting with $XULRUNNER from $APPDIR...
